package com.istloja.Vistas;

import com.istloja.Controlador.ClienteBD;
import com.istloja.Controlador.ProvedoresBD;
import com.istloja.ModelTables.ComunicacionTablas;
import com.istloja.ModelTables.ModeTableCliente;
import com.istloja.ModelTables.ModeTableProvedores;
import com.istloja.Modelo.Clientes;
import com.istloja.Modelo.Proveedores;
import com.istloja.Utilidades.Utilidades;
import java.net.MalformedURLException;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author danielmora
 */
public class VentanaPrincipal extends javax.swing.JFrame implements ComunicacionTablas {

    private Clientes clientesEditar;
    private Proveedores ProvedoresEditar;
    private ClienteBD controladorCliente;
    private ProvedoresBD controladorProvedores;
    private GestionBarClientes gestionBarClientes;
    private GestionBarPovedores gestionBarPovedores;
    private Utilidades utilidades;
    private ModeTableCliente modeTableCliente;
    private ModeTableProvedores modeTableProvedores;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {

        setResizable(true);
        setLocationRelativeTo(null);

        controladorCliente = new ClienteBD();
        controladorProvedores = new ProvedoresBD();
        modeTableCliente = new ModeTableCliente(controladorCliente.obtenerCliente(), this);
        modeTableProvedores = new ModeTableProvedores(controladorProvedores.obtenerProvedores(), this);
        initComponents();
        utilidades = new Utilidades();
        gestionBarClientes = new GestionBarClientes(txtcedulaClientes, txtnombreCliente, txtapellidoCliente, txtdireccionCliente, txttelefonoCliente, txtedadCliente, txtfechaCliente, txtartistaCliente, txtmusicaCliente, ComboBoxgeneroCliente, txtañodemusicaCliente, txtUrlCliente, this, utilidades);
        gestionBarPovedores = new GestionBarPovedores(txtRucProvedores, txtRazonSocialProvedores, txtTipodeActividadProvedores, txtNombreRepresentanteProvedores, txtApellidosProvedores, txtTelefeonoProvedores, txtCorreoProvedores, txtDireccionProvedores, ComboBoxEstadoDeudaProvedores, JDateFecharegistroProvedores, this, utilidades);
// clientesEditar = new Clientes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcedulaClientes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnombreCliente = new javax.swing.JTextField();
        txtdireccionCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtapellidoCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttelefonoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtedadCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtartistaCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtañodemusicaCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfechaCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtmusicaCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ComboBoxgeneroCliente = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtUrlCliente = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButtonGuardarCliente = new javax.swing.JButton();
        ButtonEditarCliente = new javax.swing.JButton();
        ButtonEliminarCliente = new javax.swing.JButton();
        ButtonLimoiarCajasCliente = new javax.swing.JButton();
        ComboBoxParametroBusquedaCliente = new javax.swing.JComboBox<>();
        txtPrametroBusquedaCliente = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtRucProvedores = new javax.swing.JTextField();
        txtRazonSocialProvedores = new javax.swing.JTextField();
        txtTipodeActividadProvedores = new javax.swing.JTextField();
        txtNombreRepresentanteProvedores = new javax.swing.JTextField();
        txtTelefeonoProvedores = new javax.swing.JTextField();
        txtApellidosProvedores = new javax.swing.JTextField();
        txtCorreoProvedores = new javax.swing.JTextField();
        txtDireccionProvedores = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        JDateFecharegistroProvedores = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        txtbusquedaParametroDeBusqueda = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        ComboBoxEstadoDeudaProvedores = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eston Bar Musica Danei Mora");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Clientes"));

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel1.setText("apellido");

        jLabel2.setFont(new java.awt.Font("Bebas Neue", 3, 36)); // NOI18N
        jLabel2.setText("REGISTRO CLIENTES");

        jLabel3.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel3.setText("CEDULA:");

        jLabel4.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel4.setText("nombre");

        jLabel5.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel5.setText("direccion");

        jLabel6.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel6.setText("telefono");

        jLabel7.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel7.setText("edad");

        jLabel8.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("artista");

        jLabel9.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("año");

        jLabel10.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel10.setText("fecha");

        txtfechaCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfechaClienteFocusGained(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("musica");

        jLabel12.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("url");

        ComboBoxgeneroCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Bachata", "Baladas", "Hip Hop", "Clásica", "Merengue", "Perreo", "Reggaeton", "Rock", "Salsa", "Vallenato" }));

        jLabel13.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("genero");

        txtUrlCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUrlClienteFocusGained(evt);
            }
        });

        jTable1.setModel(modeTableCliente);
        jTable1.setSelectionForeground(new java.awt.Color(204, 204, 0));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        ButtonGuardarCliente.setText("GUARDAR");
        ButtonGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarClienteActionPerformed(evt);
            }
        });

        ButtonEditarCliente.setText("EDITAR");
        ButtonEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarClienteActionPerformed(evt);
            }
        });

        ButtonEliminarCliente.setText("ELIMINAR");
        ButtonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarClienteActionPerformed(evt);
            }
        });

        ButtonLimoiarCajasCliente.setText("LIMPIAR");
        ButtonLimoiarCajasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimoiarCajasClienteActionPerformed(evt);
            }
        });

        ComboBoxParametroBusquedaCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CEDULA", "APELLIDO", "ARTISTA", "Item 4" }));

        txtPrametroBusquedaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrametroBusquedaClienteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(90, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtedadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(286, 286, 286))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtdireccionCliente))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtnombreCliente))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtartistaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtmusicaCliente))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtañodemusicaCliente)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ComboBoxgeneroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addGap(0, 78, Short.MAX_VALUE)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtfechaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtapellidoCliente)
                                                        .addComponent(txttelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUrlCliente))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcedulaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(240, 240, 240)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(ButtonGuardarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonEditarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonEliminarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonLimoiarCajasCliente)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(ComboBoxParametroBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtPrametroBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcedulaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtnombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtapellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtdireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtedadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtfechaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxgeneroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtartistaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtmusicaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtañodemusicaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUrlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonGuardarCliente)
                    .addComponent(ButtonEditarCliente)
                    .addComponent(ButtonEliminarCliente)
                    .addComponent(ButtonLimoiarCajasCliente))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxParametroBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrametroBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("REGISTROS", jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Provedores"));

        jLabel15.setFont(new java.awt.Font("Bebas Neue", 3, 36)); // NOI18N
        jLabel15.setText(" REGISTRO Povedores");

        jLabel16.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel16.setText("Ruc");

        jLabel17.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel17.setText("Razon Social");

        jLabel18.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setText("Tipo de Actividad");

        jLabel19.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 51));
        jLabel19.setText("Nombre Represnetante");

        jLabel20.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setText("Apellido Representante");

        jLabel21.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel21.setText("Telefono");

        jLabel22.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel22.setText("Correo");

        jLabel23.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel23.setText("Direccion");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        txtRazonSocialProvedores.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRazonSocialProvedoresFocusGained(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/Imagenes/provedores3.jpg"))); // NOI18N
        jLabel25.setText("jLabel25");

        jLabel24.setFont(new java.awt.Font("Bebas Neue", 3, 14)); // NOI18N
        jLabel24.setText("Fecha");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JDateFecharegistroProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(JDateFecharegistroProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setText("LIMPIAR");

        jButton2.setText("GUARDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EDITAR");

        jButton4.setText("ElIMINAR");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ruc", "Apellido", "Item 3", "Item 4" }));

        jLabel26.setFont(new java.awt.Font("Bebas Neue", 3, 24)); // NOI18N
        jLabel26.setText("Estado Deuda");

        ComboBoxEstadoDeudaProvedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuinguno", "Saldo Pendinte", "Saldo Abonado", "Total_Cancelado" }));
        ComboBoxEstadoDeudaProvedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEstadoDeudaProvedoresActionPerformed(evt);
            }
        });

        jTable3.setModel(modeTableProvedores);
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(365, 365, 365)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRucProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorreoProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefeonoProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTipodeActividadProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreRepresentanteProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidosProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRazonSocialProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDireccionProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxEstadoDeudaProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jButton2)
                                .addGap(42, 42, 42)
                                .addComponent(jButton3)
                                .addGap(46, 46, 46)
                                .addComponent(jButton4)
                                .addGap(36, 36, 36)
                                .addComponent(jButton1)
                                .addGap(127, 127, 127)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtbusquedaParametroDeBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtRucProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtRazonSocialProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtTipodeActividadProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtNombreRepresentanteProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtApellidosProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtTelefeonoProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreoProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(ComboBoxEstadoDeudaProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbusquedaParametroDeBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("PROVEDORES", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("INVENTARIO", jPanel2);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/Imagenes/formatominiatura.jpg"))); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setText("2.30");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(755, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(651, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("VENTAS", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarClienteActionPerformed
        guaardarClientes();
    }//GEN-LAST:event_ButtonGuardarClienteActionPerformed
    public void guaardarClientes() {
        if (controladorCliente.getClienteCedula(txtcedulaClientes.getText()) != null) {
            JOptionPane.showMessageDialog(rootPane, "El Cliente con ese numero de cedula ya se encuentra en el Sistema", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Clientes clientesGuardar = gestionBarClientes.validarGuardarEditar(false);

            if (clientesGuardar != null) {
                
                if (controladorCliente.registrarCliente(clientesGuardar)) {
                    
                    JOptionPane.showMessageDialog(rootPane, "Cliente Registrado Corectamente en el sistema.");
                    gestionBarClientes.lmpiarRellenoClientes();
                    actualizartodaTablaClientes();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al registrar Cliente");
                }
            }

        }
    }
    private void txtUrlClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUrlClienteFocusGained
        txtUrlCliente.copy();
        txtUrlCliente.paste();
    }//GEN-LAST:event_txtUrlClienteFocusGained

    private void ButtonLimoiarCajasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimoiarCajasClienteActionPerformed
        gestionBarClientes.lmpiarRellenoClientes();
    }//GEN-LAST:event_ButtonLimoiarCajasClienteActionPerformed

    private void txtPrametroBusquedaClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrametroBusquedaClienteKeyReleased
        System.out.println("Busqueda Parametro Clientes" + ComboBoxParametroBusquedaCliente.getSelectedItem());
        switch (ComboBoxParametroBusquedaCliente.getSelectedIndex()) {
            case 0:
                modeTableCliente.setClientes(controladorCliente.obtenerClienteCedula(txtPrametroBusquedaCliente.getText()));
                modeTableCliente.fireTableDataChanged();

                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_txtPrametroBusquedaClienteKeyReleased

    private void txtfechaClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfechaClienteFocusGained
        txtfechaCliente.setText(utilidades.devolverFechaFormato(utilidades.devolverFechaactual()));
        txtartistaCliente.requestFocus();
    }//GEN-LAST:event_txtfechaClienteFocusGained

    private void ButtonEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarClienteActionPerformed
        botonEditarClientes();
    }//GEN-LAST:event_ButtonEditarClienteActionPerformed

    private void ButtonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarClienteActionPerformed
        botonEliminarCliente();        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEliminarClienteActionPerformed

    private void ComboBoxEstadoDeudaProvedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEstadoDeudaProvedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxEstadoDeudaProvedoresActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        botonGuardarProvedores();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtRazonSocialProvedoresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazonSocialProvedoresFocusGained
        // TODO add your handling code here:xxx
        //txtfechaCliente.setText(utilidades.devolverFechaFormato(utilidades.devolverFechaactual()));
       JDateFecharegistroProvedores.setText(utilidades.devolverFechaFormato(utilidades.devolverFechaactual()));
    }//GEN-LAST:event_txtRazonSocialProvedoresFocusGained
    public void botonGuardarProvedores() {
        if (controladorProvedores.getProvedorCedula(txtRucProvedores.getText()) != null) {
            JOptionPane.showMessageDialog(rootPane, "El Provedor con ese numero de ruc  ya se encuentra en el Sistema", "Error", JOptionPane.ERROR_MESSAGE);
        }
        Proveedores proveedoresGuargar = gestionBarPovedores.guradarEditar(false);
        if (proveedoresGuargar != null) {
            
            if (controladorProvedores.registrarProvedores(proveedoresGuargar)) {
                JDateFecharegistroProvedores.setText(utilidades.devolverFechaFormato(utilidades.devolverFechaactual()));
                JOptionPane.showMessageDialog(rootPane, "Provedor Registrado Corectamente en el sistema.");
                gestionBarPovedores.LimpiarRellenoProvedores();
                actualizarTablaPovedores();
            }else{
              JOptionPane.showMessageDialog(rootPane, "Error al registrar Provedor");   
            }
        }
    }
//     Clientes clientesGuardar = gestionBarClientes.validarGuardarEditar(false);
//
//            if (clientesGuardar != null) {
//                if (controladorCliente.registrarCliente(clientesGuardar)) {
//                    JOptionPane.showMessageDialog(rootPane, "Cliente Registrado Corectamente en el sistema.");
//                    gestionBarClientes.lmpiarRellenoClientes();
//                    actualizartodaTablaClientes();
//                } else {
//                    JOptionPane.showMessageDialog(rootPane, "Error al registrar Cliente");
//                }
//            }
//
//        }

    public void botonEditarClientes() {
        if (clientesEditar == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay una Cliente seleccionado para Editar !", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Clientes clientesEditarLocal = gestionBarClientes.validarGuardarEditar(true);
        if (clientesEditarLocal != null) {
            //clientesEditarLocal.setFecha_registro(Date.valueOf(utilidades.devolverFechaFormato(utilidades.devolverFechaactual())));
            clientesEditarLocal.setIdcliente(clientesEditar.getIdcliente());
            if (controladorCliente.editarClientes(clientesEditarLocal)) {
                JOptionPane.showMessageDialog(rootPane, "Cliente editado con exito en el Sitema");
                gestionBarClientes.lmpiarRellenoClientes();
                clientesEditar = null;
                actualizartodaTablaClientes();

            } else {
                JOptionPane.showMessageDialog(rootPane, "No se pudo Editar al Cliente !", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    public void botonEliminarCliente() {
        if (clientesEditar == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay una Cliente seleccionado para Eliminar !", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (clientesEditar != null) {
            int confirmar = JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO DE ELIMINAR A ESTE REGISTRO", "confirmar salida",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirmar == JOptionPane.YES_OPTION) {
                if (clientesEditar != null) {
                    if (controladorCliente.eliminarCliente(clientesEditar)) {
                        JOptionPane.showMessageDialog(rootPane, "Cliente eliminada con éxito del sistema.");
                        gestionBarClientes.lmpiarRellenoClientes();
                        clientesEditar = null;
                        actualizartodaTablaClientes();

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "No se puede eliminar persona", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Acción cancelada", "Alerta", JOptionPane.INFORMATION_MESSAGE);

                gestionBarClientes.lmpiarRellenoClientes();
            }
        }
    }

    public void actualizartodaTablaClientes() {
        modeTableCliente.setClientes(controladorCliente.obtenerCliente());
        modeTableCliente.fireTableDataChanged();
    }                                               
    public void actualizarTablaPovedores(){
        modeTableProvedores.setProveedores(controladorProvedores.obtenerProvedores());
        modeTableProvedores.fireTableDataChanged();
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEditarCliente;
    private javax.swing.JButton ButtonEliminarCliente;
    private javax.swing.JButton ButtonGuardarCliente;
    private javax.swing.JButton ButtonLimoiarCajasCliente;
    private javax.swing.JComboBox<String> ComboBoxEstadoDeudaProvedores;
    private javax.swing.JComboBox<String> ComboBoxParametroBusquedaCliente;
    private javax.swing.JComboBox<String> ComboBoxgeneroCliente;
    private javax.swing.JTextField JDateFecharegistroProvedores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtApellidosProvedores;
    private javax.swing.JTextField txtCorreoProvedores;
    private javax.swing.JTextField txtDireccionProvedores;
    private javax.swing.JTextField txtNombreRepresentanteProvedores;
    private javax.swing.JTextField txtPrametroBusquedaCliente;
    private javax.swing.JTextField txtRazonSocialProvedores;
    private javax.swing.JTextField txtRucProvedores;
    private javax.swing.JTextField txtTelefeonoProvedores;
    private javax.swing.JTextField txtTipodeActividadProvedores;
    private javax.swing.JTextField txtUrlCliente;
    private javax.swing.JTextField txtapellidoCliente;
    private javax.swing.JTextField txtartistaCliente;
    private javax.swing.JTextField txtañodemusicaCliente;
    private javax.swing.JTextField txtbusquedaParametroDeBusqueda;
    private javax.swing.JTextField txtcedulaClientes;
    private javax.swing.JTextField txtdireccionCliente;
    private javax.swing.JTextField txtedadCliente;
    private javax.swing.JTextField txtfechaCliente;
    private javax.swing.JTextField txtmusicaCliente;
    private javax.swing.JTextField txtnombreCliente;
    private javax.swing.JTextField txttelefonoCliente;
    // End of variables declaration//GEN-END:variables

    public void clikCliente(Clientes c) {
        System.out.println("Cliente" + c.toString());
        txtcedulaClientes.setText(c.getCedula());
        txtnombreCliente.setText(c.getNombre());
        txtapellidoCliente.setText(c.getApellido());
        txtdireccionCliente.setText(c.getDirecion());
        txttelefonoCliente.setText(c.getTelefono());
        txtedadCliente.setText(c.getEdad());
        txtfechaCliente.setText(String.valueOf(c.getFecha_registro()));
        txtartistaCliente.setText(c.getArtista());
        ComboBoxgeneroCliente.setSelectedItem(c.getGenero());
        txtmusicaCliente.setText(c.getMusica());
        txtañodemusicaCliente.setText(c.getAñoMusica());
        txtUrlCliente.setText(c.getVinculo());
        clientesEditar = c;

    }

    @Override
    public void ClikProvedores(Proveedores p) {

        txtRucProvedores.setText(p.getRuc());
        txtRazonSocialProvedores.setText(p.getRazon_social());
        txtTipodeActividadProvedores.setText(p.getTipo_actividad());
        txtNombreRepresentanteProvedores.setText(p.getNombre_representante());
        txtApellidosProvedores.setText(p.getApellido_representante());
        txtTelefeonoProvedores.setText(p.getTelefono());
        txtCorreoProvedores.setText(p.getCorreo());
        txtDireccionProvedores.setText(p.getDireccion());
        ComboBoxEstadoDeudaProvedores.setSelectedIndex(0);
        JDateFecharegistroProvedores.setText(String.valueOf(p.getFecha_Registro()));

        ProvedoresEditar = p;
    }
}
